logging:
  level:
    liquibase: debug
    org.springframework.batch: info
    com.broadcom.springconsulting.batch: debug

spring:
  application:
    name: batch-demo

  batch:
    jdbc:
      initialize-schema: never

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  management:
    metrics:
      export:
        prometheus:
          enabled: true
          pushgateway:
            enabled: true
            base-url: http://prometheus-pushgateway.observability.svc.cluster.local:9091
            job: ${spring.application.name}
