logging:
  level:
    liquibase: debug
    org.springframework.batch: debug
    org.springframework.jdbc: debug
    com.broadcom.springconsulting.batch: debug

spring:
  application:
    name: batch-demo

  batch:
    jdbc:
      initialize-schema: never

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  threads:
    virtual:
      enabled: true

management:
  prometheus:
    metrics:
      export:
        enabled: true
        pushgateway:
          enabled: true
          address: prometheus-pushgateway.observability.svc.cluster.local:9091
          job: ${spring.application.name}
