logging:
  level:
    liquibase: info
    org.springframework.batch: info
    org.springframework.jdbc: info
    com.broadcom.springconsulting.batch: debug

spring:
  application:
    name: batch-demo

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  cloud:
    function:
      definition: fileSupplier

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  sql:
    init:
      mode: never

  threads:
    virtual:
      enabled: true

file:
  consumer:
    mode: ref
  supplier:
    directory: # Set some real dir with zips to process
    filename-pattern: '*.csv'

splitter:
  charset: UTF-8

management:
  prometheus:
    metrics:
      export:
        enabled: false
        pushgateway:
          enabled: true
          address: prometheus-pushgateway.observability.svc.cluster.local:9091
          job: ${spring.application.name}
